import ImageIcon from '@mui/icons-material/Image';
import NotesOutlinedIcon from '@mui/icons-material/NotesOutlined';
import FormIcon from '@mui/icons-material/Description';
import HeaderIcon from '@mui/icons-material/TextFormat';
import CodeIcon from '@mui/icons-material/Code';
import ButtonIcon from '@mui/icons-material/EditAttributes';
import ToggleOffOutlinedIcon from '@mui/icons-material/ToggleOffOutlined';
import LinkIcon from '@mui/icons-material/Link';
import FormatListBulletedOutlinedIcon from '@mui/icons-material/FormatListBulletedOutlined';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import FormatListNumberedOutlinedIcon from '@mui/icons-material/FormatListNumberedOutlined';
import FeaturedPlayListOutlinedIcon from '@mui/icons-material/FeaturedPlayListOutlined';
import ListAltOutlinedIcon from '@mui/icons-material/ListAltOutlined';
import RouteOutlinedIcon from '@mui/icons-material/RouteOutlined';
import DatasetLinkedOutlinedIcon from '@mui/icons-material/DatasetLinkedOutlined';
import ShortTextOutlinedIcon from '@mui/icons-material/ShortTextOutlined';
import MoreOutlinedIcon from '@mui/icons-material/MoreOutlined';

import {
  HTMLType
} from '../interfaces/Interfaces';

//properties for all HTML components

const HTMLTypes: HTMLType[] = [
  {
    id: 11,
    tag: 'div',
    name: 'Div',
    style: {},
    placeHolderShort: 'div',
    placeHolderLong: '',
    icon: CodeIcon,
    framework: 'reactClassic',
    nestable: true,
  },
  // do not move this separator element out of index 1 in this array
  // in componentReducer.ts, separator is referenced as 'initialState.HTMLTypes[1]'
  {
    id: 1000,
    tag: 'separator',
    name: 'separator',
    style: { border: 'none' },
    placeHolderShort: '',
    placeHolderLong: '',
    icon: '',
    framework: '',
    nestable: true,
  },
  {
    id: 1,
    tag: 'img',
    name: 'Img',
    style: {},
    placeHolderShort: 'image',
    placeHolderLong: '',
    icon: ImageIcon,
    framework: 'reactClassic',
    nestable: false,
  },
  {
    id: 2,
    tag: 'form',
    name: 'Form',
    style: {},
    placeHolderShort: 'form',
    placeHolderLong: '',
    icon: FormIcon,
    framework: 'reactClassic',
    nestable: true,
  },
  {
    id: 4,
    tag: 'button',
    name: 'Button',
    style: {},
    placeHolderShort: 'button',
    placeHolderLong: '',
    icon: ButtonIcon,
    framework: 'reactClassic',
    nestable: false,
  },
  {
    id: 6,
    tag: 'a',
    name: 'Link',
    style: {},
    placeHolderShort: 'link',
    placeHolderLong: '',
    icon: LinkIcon,
    framework: 'reactClassic',
    nestable: false,
  },
  {
    id: 8,
    tag: 'p',
    name: 'Paragraph',
    style: {},
    placeHolderShort: 'paragraph',
    placeHolderLong: '',
    icon: NotesOutlinedIcon,
    framework: 'reactClassic',
    nestable: false,
  },
  {
    id: 9,
    tag: 'h1',
    name: 'Header 1',
    style: {},
    placeHolderShort: 'header 1',
    placeHolderLong: '',
    icon: HeaderIcon,
    framework: 'reactClassic',
    nestable: false,
  },
  {
    id: 10,
    tag: 'h2',
    name: 'Header 2',
    style: {},
    placeHolderShort: 'header 2',
    placeHolderLong: '',
    icon: HeaderIcon,
    framework: 'reactClassic',
    nestable: false,
  },
  {
    id: 5,
    tag: 'span',
    name: 'Span',
    style: {},
    placeHolderShort: 'span',
    placeHolderLong: '',
    icon: ShortTextOutlinedIcon,
    framework: 'reactClassic',
    nestable: false,
  },
  {
    id: 12,
    tag: 'input',
    name: 'Input',
    style: {},
    placeHolderShort: 'input',
    placeHolderLong: '',
    icon: EditOutlinedIcon,
    framework: 'reactClassic',
    nestable: false,
  },
  {
    id: 13,
    tag: 'label',
    name: 'Label',
    style: {},
    placeHolderShort: 'label',
    placeHolderLong: '',
    icon: MoreOutlinedIcon,
    framework: 'reactClassic',
    nestable: false,
  },
  {
    id: 14,
    tag: 'ol',
    name: 'Ordered List',
    style: {},
    placeHolderShort: 'ordered list',
    placeHolderLong: '',
    icon: FormatListNumberedOutlinedIcon,
    framework: 'reactClassic',
    nestable: true,
  },
  {
    id: 15,
    tag: 'ul',
    name: 'Unordered List',
    style: {},
    placeHolderShort: 'unordered list',
    placeHolderLong: '',
    icon: FormatListBulletedOutlinedIcon,
    framework: 'reactClassic',
    nestable: true,
  },
  {
    id: 16,
    tag: 'menu',
    name: 'Menu',
    style: {},
    placeHolderShort: 'menu',
    placeHolderLong: '',
    icon: FeaturedPlayListOutlinedIcon,
    framework: 'reactClassic',
    nestable: true,
  },
  {
    id: 3,
    tag: 'li',
    name: 'List',
    style: {},
    placeHolderShort: 'list item',
    placeHolderLong: '',
    icon: ListAltOutlinedIcon,
    framework: 'reactClassic',
    nestable: true,
  },
  {
    id: 17,
    tag: 'Switch',
    name: 'Switch',
    style: {},
    placeHolderShort: 'Switch',
    placeHolderLong: '',
    icon: ToggleOffOutlinedIcon,
    framework: 'reactClassic',
    nestable: true,
  },
  {
    id: -1,
    tag: 'Route',
    name: 'Route',
    style: {},
    placeHolderShort: 'Route',
    placeHolderLong: '',
    icon: RouteOutlinedIcon,
    framework: 'reactClassic',
    nestable: true,
  },
  {
    id: 18,
    tag: 'Link',
    name: 'LinkTo',
    style: {},
    placeHolderShort: 'LinkTo',
    placeHolderLong: '',
    icon: DatasetLinkedOutlinedIcon,
    framework: 'reactClassic',
    nestable: true,
  },
  {
    id: 19,
    tag: 'Link',
    name: 'LinkHref',
    style: {},
    placeHolderShort: 'LinkHref',
    placeHolderLong: '',
    icon: LinkIcon,
    framework: 'nextjs',
    nestable: true,
  },
  {
    id: 20,
    tag: 'Image',
    name: 'Image',
    style: {},
    placeHolderShort: 'Image',
    placeHolderLong: '',
    icon: ImageIcon,
    framework: 'nextjs',
    nestable: false,
  },
];
export default HTMLTypes;
