// save all action as constants here
export const DARK_MODE_TOGGLE = 'DARK_MODE_TOGGLE';
export const CODE_PREVIEW_SAVE = 'CODE_PREVIEW_SAVE';
export const CODE_PREVIEW_INPUT = 'CODE_PREVIEW_INPUT';
export const ADD_CONTEXT = 'ADD_CONTEXT';
export const ADD_CONTEXT_VALUES = 'ADD_CONTEXT_VALUES';
export const ADD_COMPONENT_TO_CONTEXT = 'ADD_COMPONENT_TO_CONTEXT';
export const DELETE_CONTEXT = 'DELETE_CONTEXT';
export const GET_ALL_CONTEXT = 'GET_ALL_CONTEXT';
